<a href="https://colab.research.google.com/github/RajBharti25/Codalab-Sentiment-Ananlysis-/blob/master/CodaLab_EI_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
!pwd

/content


In [0]:
cd gdrive/My Drive/Colab Notebooks/CodaLab/working_directory

/content/gdrive/My Drive/Colab Notebooks/CodaLab/working_directory


In [0]:
import numpy as np
np.random.seed(0)
from keras.models import Model
from keras import optimizers
from keras.layers import Dense,Input,Dropout,LSTM,Activation
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from keras.initializers import glorot_uniform
np.random.seed(1)

In [0]:
file1=open(r"/content/gdrive/My Drive/Colab Notebooks/CodaLab/EI-reg-En-train/EI-reg-En-anger-train.txt")

In [0]:
ID = []
Tweet = []
Affect_Dimension = []
Score = []
lines=file1.read()
for line in lines.split('\n'):
  item=line.split('\t')
  if(len(item)<4):
      continue
  ID.append(item[0])
  Tweet.append(item[1])
  Affect_Dimension.append(item[2])
  Score.append(item[3])
file1.close()

In [0]:
import pandas as pd
df = pd.DataFrame(columns =['ID','Tweet','Affect','Score'])
df['ID']=ID
df['Tweet']=Tweet
df['Affect'] = Affect_Dimension
df['Score']=Score
df.head()
df.drop(axis=0,index=0, inplace=True)
df.to_csv('Data.csv')
df.head(10)
d1=np.array(Tweet)

In [0]:
import re
import nltk
nltk.download('wordnet')
wnl = nltk.WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [0]:
X=df['Tweet']
Y=df['Score']
X=X[:].apply(lambda x:x.lower())
X=X[:].apply(lambda x:re.sub(r'@(?i)[a-zA-Z0-9_]+','',x))
X=X[:].apply(lambda x:re.sub('[^a-zA-z0-9\s]','',x))
print(X[1])
X=X[:].apply(lambda x:x.strip())
print(X[1])
print(X[2])
print(X[3])
print(X[4])
print(X[5])

  shut up hashtags are cool offended
shut up hashtags are cool offended
it makes me so fucking irate jesus nobody is calling ppl who like hajime abusive stop with the strawmen lmao
lol adam the bull with his fake outrage
passed away early this morning in a fast and furious styled car crash as he was leaving an atl strip club thats rough stuff
lol wow i was gonna say really haha have you seen chris or nah you dont even snap me anymore dude


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: Flags not at the start of the expression '@(?i)[a-zA-Z0-9_]+'
  after removing the cwd from sys.path.


In [0]:
X=X[:].apply(lambda x:x.split())
print(X[1])
print(X[2])
print(X[3])
print(X[4])
print(X[5])
print('\n\n')
X1=X[:].apply(lambda x:wnl.lemmatize(str(x[:])))
print(X1[1])
print(X1[2])
print(X1[3])
print(X1[5])

['shut', 'up', 'hashtags', 'are', 'cool', 'offended']
['it', 'makes', 'me', 'so', 'fucking', 'irate', 'jesus', 'nobody', 'is', 'calling', 'ppl', 'who', 'like', 'hajime', 'abusive', 'stop', 'with', 'the', 'strawmen', 'lmao']
['lol', 'adam', 'the', 'bull', 'with', 'his', 'fake', 'outrage']
['passed', 'away', 'early', 'this', 'morning', 'in', 'a', 'fast', 'and', 'furious', 'styled', 'car', 'crash', 'as', 'he', 'was', 'leaving', 'an', 'atl', 'strip', 'club', 'thats', 'rough', 'stuff']
['lol', 'wow', 'i', 'was', 'gonna', 'say', 'really', 'haha', 'have', 'you', 'seen', 'chris', 'or', 'nah', 'you', 'dont', 'even', 'snap', 'me', 'anymore', 'dude']



['shut', 'up', 'hashtags', 'are', 'cool', 'offended']
['it', 'makes', 'me', 'so', 'fucking', 'irate', 'jesus', 'nobody', 'is', 'calling', 'ppl', 'who', 'like', 'hajime', 'abusive', 'stop', 'with', 'the', 'strawmen', 'lmao']
['lol', 'adam', 'the', 'bull', 'with', 'his', 'fake', 'outrage']
['lol', 'wow', 'i', 'was', 'gonna', 'say', 'really', 'haha',

In [0]:
max_len=len(max(X[:],key=len))
max_len

31

In [0]:
X2=pd.DataFrame(X1)
X2.reset_index(drop=True,inplace=True)
X2.head()

Tweet
0  ['shut', 'up', 'hashtags', 'are', 'cool', 'off...
1  ['it', 'makes', 'me', 'so', 'fucking', 'irate'...
2  ['lol', 'adam', 'the', 'bull', 'with', 'his', ...
3  ['passed', 'away', 'early', 'this', 'morning',...
4  ['lol', 'wow', 'i', 'was', 'gonna', 'say', 're...

In [0]:
UNK_value=[-0.12920076, -0.28866628, -0.01224866, -0.05676644, -0.20210965, -0.08389011,
      0.33359843,  0.16045167,  0.03867431,  0.17833012,  0.04696583, -0.00285802,
      0.29099807,  0.04613704, -0.20923874, -0.06613114, -0.06822549,  0.07665912,
      0.3134014,   0.17848536, -0.1225775,  -0.09916984, -0.07495987,  0.06413227,
      0.14441176,  0.60894334,  0.17463093,  0.05335403, -0.01273871,  0.03474107,
      -0.8123879,  -0.04688699,  0.20193407,  0.2031118,  -0.03935686,  0.06967544,
      -0.01553638, -0.03405238, -0.06528071,  0.12250231,  0.13991883, -0.17446303,
      -0.08011883,  0.0849521,  -0.01041659, -0.13705009,  0.20127155,  0.10069408,
       0.00653003,  0.01685157]

In [0]:
def read_glove_vecs(glove_file):
    with open(glove_file, 'r') as f:
        words = set()
        word_to_vec_map = {}
        for line in f:
            line = line.strip().split()
            curr_word = line[0]
            words.add(curr_word)
            word_to_vec_map[curr_word] = np.array(line[1:], dtype=np.float64)
        
        i = 1
        words_to_index = {}
        index_to_words = {}
        for w in sorted(words):
            words_to_index[w] = i
            index_to_words[i] = w
            i = i + 1
        words=sorted(words)
        words.append('<unk>')
        words_to_index['<unk>']=i
        index_to_words[i] = '<unk>'
        word_to_vec_map['<unk>']=UNK_value

    return sorted(words),words_to_index, index_to_words, word_to_vec_map

In [0]:
words_set,word_to_index, index_to_word, word_to_vec_map = read_glove_vecs(r'glove.6B.50d.txt')

In [0]:
if('<unk>' in words_set):
  print('true')
else:
  print('false')

true


In [0]:
def convert_to_one_hot(Y, C):
    Y = np.eye(C)[Y.reshape(-1)]
    return Y

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()


In [0]:
word = "king"
idx = 289846
print("the index of", word, "in the vocabulary is", word_to_index[word])
print("the", str(idx) + "th word in the vocabulary is", index_to_word[idx])

the index of king in the vocabulary is 207802
the 289846th word in the vocabulary is potatos


In [0]:
#sentence to indices function so that each word can be embedded with embedding vector
def sentence_to_indices(X,word_to_index,max_len,words_set):
  m=X.shape[0]
  X_indices=np.zeros(shape=(m,max_len))
  for i in range(m):
    sentence=X[i]
    sentence=re.sub(r'@(?i)[a-zA-Z0-9_]+','',sentence)
    sentence=re.sub('[^a-zA-z0-9\s]','',sentence)
    words=sentence.lower().strip().split()
    
    j=0
    for w in words:
      if(w in words_set):
        X_indices[i,j]=word_to_index[w]
        j=j+1
      else:
        X_indices[i,j]=word_to_index['<unk>']
        j=j+1
  return X_indices

In [0]:
sen1="Ram Was excellent boy"
sen2="shyam was a bad boy"
sen=np.array((sen1,sen2))
sen1=sentence_to_indices(sen,word_to_index,20,words_set)
sen1

array([[299863., 383514., 142331.,  82265.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.],
       [330581., 383514.,  43010.,  65963.,  82265.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.]])

In [0]:
X_train=np.array(Tweet)
print(X_train[0])
X_train=np.delete(X_train,0,0)
print(X_train[0])
Y_train=np.array(Score)
print(Y_train[0])
Y_train=np.delete(Y_train,0,0)
Y_train.reshape(-1,1)
print(Y_train[0])

Tweet
@xandraaa5 @amayaallyn6 shut up hashtags are cool #offended
Intensity Score
0.562


In [0]:
# EMBEDDING LAYER USING PRETRAINED VECTORS
def pretrained_embedding_layer(word_to_vec_map, word_to_index):
  vocab_len=len(word_to_index)+1
  emb_dim=word_to_vec_map['he'].shape[0]
  emb_matrix=np.zeros(shape=(vocab_len, emb_dim))
  for word, idx in word_to_index.items():
        emb_matrix[idx, :] = word_to_vec_map[word]
  
  embedding_layer = Embedding(vocab_len, emb_dim, trainable=False)
  embedding_layer.build((None,))
  embedding_layer.set_weights([emb_matrix])
  return embedding_layer

In [0]:
embedding_layer = pretrained_embedding_layer(word_to_vec_map, word_to_index)
print("weights[0][1][3] =", embedding_layer.get_weights()[0][1][3])










weights[0][1][3] = -0.3403


In [0]:
#LSTM based classifier model
def LSTM_model(input_shape, word_to_vec_map, word_to_index):
  sentence_indices=Input(input_shape,dtype='int32')
  embedding_layer=pretrained_embedding_layer(word_to_vec_map, word_to_index)
  embeddings=embedding_layer(sentence_indices)
  X = LSTM(64, return_sequences=True)(embeddings)
  X = Dropout(0.5)(X)
  X = LSTM(64, return_sequences=False)(X)
  #X = Dropout(0.5)(X)
  X = Dense(1)(X)
  X = Activation('sigmoid')(X)
  model = Model(inputs=sentence_indices, outputs=X)
  return model

In [0]:
model = LSTM_model((45,), word_to_vec_map, word_to_index)
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 45)                0         
_________________________________________________________________
embedding_4 (Embedding)      (None, 45, 50)            20000100  
_________________________________________________________________
lstm_5 (LSTM)                (None, 45, 64)            29440     
_________________________________________________________________
dropout_3 (Dropout)          (None, 45, 64)            0         
_________________________________________________________________
lstm_6 (LSTM)                (None, 64)                33024     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
_________________________________________________________________
activation_3 (Activation)    (None, 1)                 0   

In [0]:
adam=optimizers.adam(lr=0.001)
model.compile(loss='mse', optimizer=adam, metrics=['mse'])

In [0]:
X_train_indices=sentence_to_indices(X_train,word_to_index,45,words_set)

KeyboardInterrupt: ignored

In [0]:
model.fit(X_train_indices, Y_train, epochs = 30, batch_size = 32, shuffle=False)

Epoch 1/30
1701/1701 [==============================] - 4s 2ms/step - loss: 0.0010 - mean_squared_error: 0.0010
Epoch 2/30
1701/1701 [==============================] - 4s 2ms/step - loss: 9.5447e-04 - mean_squared_error: 9.5447e-04
Epoch 3/30
1701/1701 [==============================] - 4s 2ms/step - loss: 9.3658e-04 - mean_squared_error: 9.3658e-04
Epoch 4/30
1701/1701 [==============================] - 4s 2ms/step - loss: 9.8135e-04 - mean_squared_error: 9.8135e-04
Epoch 5/30
1701/1701 [==============================] - 4s 2ms/step - loss: 0.0011 - mean_squared_error: 0.0011
Epoch 6/30
1701/1701 [==============================] - 4s 2ms/step - loss: 0.0012 - mean_squared_error: 0.0012
Epoch 7/30
1701/1701 [==============================] - 4s 2ms/step - loss: 0.0010 - mean_squared_error: 0.0010
Epoch 8/30
1701/1701 [==============================] - 4s 2ms/step - loss: 0.0011 - mean_squared_error: 0.0011
Epoch 9/30
1701/1701 [==============================] - 4s 2ms/step - loss: 0.00

In [0]:
Tweet[5]

'@Kristiann1125 lol wow i was gonna say really?! haha have you seen chris or nah? you dont even snap me anymore dude!'

In [0]:
a=np.array((Tweet[10],Tweet[11]))

In [0]:
a1=sentence_to_indices(a,word_to_index,45,words_set)

In [0]:
model.predict(a1)

array([[0.13794178],
       [0.22454025]], dtype=float32)

In [0]:
print(Score[10])
print(Score[11])

0.125
0.231


In [0]:
file2=open(r"/content/gdrive/My Drive/Colab Notebooks/CodaLab/working_directory/2018-EI-reg-En-anger-dev.txt")
Tweet1 = []
Score1 = []
lines=file2.read()
for line in lines.split('\n'):
  item=line.split('\t')
  if(len(item)<4):
      continue
  Tweet1.append(item[1])
  Score1.append(item[3])
  file2.close()

In [0]:
X_dev=np.array(Tweet1)
print(X_dev[0])
X_dev=np.delete(X_dev,0,0)
print(X_dev[0])
Y_dev=np.array(Score1)
print(Y_dev[0])
Y_dev=np.delete(Y_dev,0,0)
Y_dev.reshape(-1,1)
print(Y_dev[0])

Tweet
'we need to do something. something must be done!!!!!'\n\nyour anxiety is amusing. nothing will be done. despair.
Intensity Score
0.517


In [0]:
X_dev_indices=sentence_to_indices(X_dev,word_to_index,45,words_set)
X_dev_indices[1:5]

array([[384630.,  71090., 155179., 186645., 357266., 178700., 272881.,
         40701., 251014., 151349.,  43010., 305014., 155017.,  65680.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [ 89686., 170714.,  43010., 261192.,  44608., 397971., 185457.,
        170714.,  43010., 129149.,  44608., 153510.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [103493., 302352., 258481., 360915., 160418., 272930., 268046.,
     

In [0]:
X_dev_pred=model.predict(X_dev_indices)

In [0]:
X_dev_pred=X_dev_pred.reshape(-1,1)
Y_dev=Y_dev.reshape(-1,1)

In [0]:
result=np.array((Y_dev,X_dev_pred))

In [0]:
result=result.reshape(-1,2)

In [0]:
X_dev_pred[1:5]

array([[0.57835877],
       [0.59811497],
       [0.77330077],
       [0.57955915]], dtype=float32)

In [0]:
Y_dev[1:5]

array([['0.726'],
       ['0.250'],
       ['0.641'],
       ['0.313']], dtype='<U15')

In [0]:
Tweet1[1]

"'we need to do something. something must be done!!!!!'\\n\\nyour anxiety is amusing. nothing will be done. despair."

In [0]:
Score1[1]

'0.517'

In [0]:
a=np.array((Tweet1[1],Tweet1[2]))
a1=sentence_to_indices(a,word_to_index,45,words_set)

In [0]:
a1

array([[384374., 258451., 360915., 126552., 337302., 337302., 253767.,
         71090., 400001.,  57164., 192973.,  54224., 264612., 387696.,
         71090., 127491., 121937.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [384630.,  71090., 155179., 186645., 357266., 178700., 272881.,
         40701., 251014., 151349.,  43010., 305014., 155017.,  65680.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.]])

In [0]:
model.predict(a1)

array([[0.44257084],
       [0.61536044]], dtype=float32)

In [0]:
file2=open(r"/content/gdrive/My Drive/Colab Notebooks/CodaLab/working_directory/2018-EI-reg-En-anger-dev.txt")
file2.read()

"ID\tTweet\tAffect Dimension\tIntensity Score\n2018-En-01052\t'we need to do something. something must be done!!!!!'\\n\\nyour anxiety is amusing. nothing will be done. despair.\tanger\t0.517\n2018-En-03440\t@Chan_lfc10 @paul_rule @Nuttall1878 @DeadlineDayLive @Everton We'd be fuming if the hijacked our £8m move for a relegated full back 😡\tanger\t0.726\n2018-En-01489\tCaleb had a nightmare about zombies. I had a dream about freedom.......\tanger\t0.250\n2018-En-00490\t#CNN really needs to get out of the #Propaganda Business.. 30 seconds on USN fallen Soldiers tragedy. Right back at spewing #hatred #POTUS\tanger\t0.641\n2018-En-02178\t#dmme #kikme  #sext #horny  #ass #bbw  #naughty  #pussy #kik   #nudes  only  girls  😩 horny  #snap    jacobgigs\tanger\t0.313\n2018-En-02533\tDon't fucking tag me in pictures as 'family first' when you cut me out 5 years ago. You're no one to me. \tanger\t0.953\n2018-En-03360\tCoulda sworn it was Interview With A Vampire. Hmmm......Mandela Effect anyone? 

In [0]:
X_dev[0]

"'we need to do something. something must be done!!!!!'\\n\\nyour anxiety is amusing. nothing will be done. despair."

In [0]:
Y_dev[1]

NameError: ignored

In [0]:
a=X_dev[:2]
a

array(["'we need to do something. something must be done!!!!!'\\n\\nyour anxiety is amusing. nothing will be done. despair.",
       "@Chan_lfc10 @paul_rule @Nuttall1878 @DeadlineDayLive @Everton We'd be fuming if the hijacked our £8m move for a relegated full back 😡"],
      dtype='<U152')

In [0]:
a1=sentence_to_indices(a,word_to_index,45,words_set)

In [0]:
a1

array([[384374., 258451., 360915., 126552., 337302., 337302., 253767.,
         71090., 400001.,  57164., 192973.,  54224., 264612., 387696.,
         71090., 127491., 121937.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.],
       [384630.,  71090., 155179., 186645., 357266., 178700., 272881.,
         40701., 251014., 151349.,  43010., 305014., 155017.,  65680.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.,      0.,      0.,      0.,      0.,
             0.,      0.,      0.]])

In [0]:
index_to_word[384630]

'wed'

In [0]:
Y_dev[:2]

array(['0.517', '0.726'], dtype='<U15')

In [0]:
model.predict(a1)

NameError: ignored